// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLiteMinecraftApi.Context;

#nullable disable

namespace SQLiteMinecraftApi.Migrations
{
    [DbContext(typeof(MinecraftContext))]
    [Migration("20250105064641_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SQLiteMinecraftApi.Context.MinecraftItem", b =>
                {
                    b.Property<string>("UUID")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("item1")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("item2")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("item3")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("item4")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("item5")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("item6")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("item7")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("item8")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("item9")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("minecraftitems", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
